version: "3"

networks:
  loki:

volumes:
  grafana-data:

services:
  loki:
    image: grafana/loki:1.4.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - loki
    volumes:
      - grafana-data:/var/lib/grafana

  grafana:
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    networks:
      - loki

  # promtail:
  #   image: grafana/promtail:1.4.1
  #   volumes:
  #     - /var/lib/docker/containers:/var/lib/docker/containers
  #     - ./promtail-config.yml:/etc/promtail/promtail-config.yml
  #   command: -config.file=/etc/promtail/promtail-config.yml
  #   networks:
  #     - loki
