version: "3.8"

networks:
  kepo:

volumes:
  grafana-data:

services:
  loki:
    image: grafana/loki:1.4.1
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - kepo

  prometheus:
    image: prom/prometheus
    ports:
      -"9090:9090"
    networks:
      - kepo
    volumes:
      - ./config/prometheus-config.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    networks:
      - kepo
    volumes:
      - grafana-data:/var/lib/grafana

  # promtail:
  #   image: grafana/promtail:1.4.1
  #   volumes:
  #     - /var/lib/docker/containers:/var/lib/docker/containers
  #     - ./promtail-config.yml:/etc/promtail/promtail-config.yml
  #   command: -config.file=/etc/promtail/promtail-config.yml
  #   networks:
  #     - kepo
